In [11]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv('apple_data.csv')
df

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct.1,Sale_Event,Stock_Status,Rating,Reviews_Count
0,19-09-2020,Flipkart,Watch,Apple Watch Series 6,New,429,42042,435.81,43322.41,-0.016,NaN,In Stock,4.7,40
1,20-09-2020,Flipkart,Watch,Apple Watch Series 6,New,429,42042,436.49,42320.43,-0.017,NaN,Out of Stock,4.6,84
2,23-09-2020,Amazon,Watch,Apple Watch Series 6,New,429,42042,422.73,40879.36,0.015,NaN,In Stock,4.4,110
3,23-09-2020,Amazon,Watch,Apple Watch Series 6,New,429,42042,425.00,42008.70,0.009,NaN,In Stock,4.8,111
4,24-09-2020,Amazon,Watch,Apple Watch Series 6,New,429,42042,436.22,41984.28,-0.017,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,31-07-2026,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-0.015,NaN,In Stock,4.7,1346
79996,31-07-2026,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,0.019,NaN,In Stock,4.7,802
79997,31-07-2026,Amazon,iPhone,iPhone 17 128GB,Referbished,849,83202,657.30,56336.73,0.226,NaN,In Stock,4.2,1020
79998,31-07-2026,Flipkart,iPhone,iPhone 17 128GB,Referbished,849,83202,709.49,61361.07,0.164,NaN,In Stock,3.9,710
79999,31-07-2026,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,0.017,NaN,Low Stock,4.8,1022

In [13]:
df.shape

(80000, 14)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  str
 1   Platform           80000 non-null  str
 2   Product_Category   80000 non-null  str
 3   Model_Name         80000 non-null  str
 4   Condition          80000 non-null  str
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct.1     80000 non-null  float64
 10  Sale_Event         6649 non-null   str
 11  Stock_Status       80000 non-null  str
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), str(7)
memory usage: 8.5 MB

In [15]:
df.describe().round(2)

,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct.1,Rating,Reviews_Count
count,80000.00,80000.00,80000.00,80000.00,80000.00,80000.00,80000.00
mean,963.96,94467.99,782.77,74628.34,0.21,4.45,2406.00
std,470.09,46068.47,461.67,45117.87,0.17,0.27,1973.63
min,329.00,32242.00,109.93,9157.68,-0.02,3.80,10.00
25%,599.00,58702.00,432.93,41686.84,0.07,4.30,896.00
50%,799.00,78302.00,699.74,67324.02,0.21,4.40,1893.50
75%,1199.00,117502.00,989.11,96568.12,0.37,4.70,3383.00
max,1999.00,195902.00,2038.97,203668.71,0.73,4.90,11526.00

In [16]:
df.describe(include='str')

,Date,Platform,Product_Category,Model_Name,Condition,Sale_Event,Stock_Status
count,80000,80000,80000,80000,80000,6649,80000
unique,2130,2,4,31,2,4,3
top,11-06-2025,Flipkart,iPhone,iPhone 14 Pro 128GB,New,Black Friday,In Stock
freq,95,40043,28589,2734,59985,2497,55034

In [17]:
df.columns.tolist()

['Date',
 'Platform',
 'Product_Category',
 'Model_Name',
 'Condition',
 'Launch_Price_USD',
 'Launch_Price_INR',
 'Current_Price_USD',
 'Current_Price_INR',
 'Discount_Pct.1',
 'Sale_Event',
 'Stock_Status',
 'Rating',
 'Reviews_Count']

In [18]:
df.dtypes

Date                     str
Platform                 str
Product_Category         str
Model_Name               str
Condition                str
Launch_Price_USD       int64
Launch_Price_INR       int64
Current_Price_USD    float64
Current_Price_INR    float64
Discount_Pct.1       float64
Sale_Event               str
Stock_Status             str
Rating               float64
Reviews_Count          int64
dtype: object

In [19]:
df.isnull().sum()

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct.1           0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

In [20]:
df.isnull().sum() / len(df)*100

Date                  0.00000
Platform              0.00000
Product_Category      0.00000
Model_Name            0.00000
Condition             0.00000
Launch_Price_USD      0.00000
Launch_Price_INR      0.00000
Current_Price_USD     0.00000
Current_Price_INR     0.00000
Discount_Pct.1        0.00000
Sale_Event           91.68875
Stock_Status          0.00000
Rating                0.00000
Reviews_Count         0.00000
dtype: float64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.nunique()

Date                  2130
Platform                 2
Product_Category         4
Model_Name              31
Condition                2
Launch_Price_USD         9
Launch_Price_INR         9
Current_Price_USD    49611
Current_Price_INR    79626
Discount_Pct.1         695
Sale_Event               4
Stock_Status             3
Rating                  12
Reviews_Count         8698
dtype: int64

In [23]:
df['Model_Name'].unique()

<StringArray>
[           'Apple Watch Series 6 ',          'iPad Air (4th Gen) 64GB',
                   'iPhone 12 64GB',              'iPhone 12 Pro 128GB',
             'MacBook Air M1 256GB',      'iPad Pro 11-inch (M1) 128GB',
                  'iPhone 13 128GB',          'iPhone 13 Pro Max 256GB',
              'iPad (9th Gen) 64GB',      'Apple Watch Series 7 (45mm)',
 'MacBook Pro 14-inch M1 Pro 512GB',          'iPad Air (5th Gen) 64GB',
             'MacBook Air M2 256GB',      'Apple Watch Series 8 (45mm)',
                  'iPhone 14 128GB',              'iPhone 14 Pro 128GB',
                'Apple Watch Ultra',    'iPad Pro 12.9-inch (M2) 256GB',
 'MacBook Pro 14-inch M2 Pro 512GB',      'Apple Watch Series 9 (45mm)',
              'Apple Watch Ultra 2',                  'iPhone 15 128GB',
          'iPhone 15 Pro Max 256GB', 'MacBook Pro 14-inch M3 Pro 512GB',
             'MacBook Air M3 256GB',      'iPad Pro 11-inch (M4) 256GB',
                  'iPhone 16 128GB',              'iPhone 16 Pro 256GB',
      'Apple Watch Series X (45mm)', 'MacBook Pro 14-inch M4 Pro 512GB',
                  'iPhone 17 128GB']
Length: 31, dtype: str

In [24]:
df['Sale_Event'].unique()

<StringArray>
[nan, 'Big Billion Days', 'Great Indian Festival', 'Black Friday',
 'Prime Day']
Length: 5, dtype: str

In [25]:
df['Sale_Event'].value_counts()

Sale_Event
Black Friday             2497
Big Billion Days         1579
Great Indian Festival    1504
Prime Day                1069
Name: count, dtype: int64

In [26]:
df['Model_Name'].value_counts().head(5)

Model_Name
iPhone 14 Pro 128GB            2734
iPad Air (4th Gen) 64GB        2677
iPad Pro 11-inch (M1) 128GB    2661
iPhone 17 128GB                2652
iPhone 16 Pro 256GB            2635
Name: count, dtype: int64

In [27]:
df['Sale_Event'].value_counts(normalize=True)*100

Sale_Event
Black Friday             37.554519
Big Billion Days         23.747932
Great Indian Festival    22.619943
Prime Day                16.077606
Name: proportion, dtype: float64

In [28]:
df['Product_Category'].value_counts(normalize=True)*100

Product_Category
iPhone    35.73625
Mac       22.52500
Watch     22.33125
iPad      19.40750
Name: proportion, dtype: float64

In [35]:
Q1 = df ['launch_price_usd'] .quantile (0.25)
Q3 = df ['launch_price_usd'] .quantile (0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR 
upper = Q3 +1.5 * IQR
outlier =  df [( df['launch_price_usd'] < lower) | (df['launch_price_usd']> upper)]
print ( f"{len(outlier)} outlier found")
outlier['product_category'].value_counts()

0 outlier found

Series([], Name: count, dtype: int64)

In [43]:
Q1 = df ['current_price_usd'] .quantile (0.25)
Q3 = df ['current_price_usd'] .quantile (0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR 
upper = Q3 +1.5 * IQR
outlier =  df [( df['current_price_usd'] < lower) | (df['current_price_usd']> upper)]
print ( f"{len(outlier)} outlier found")
outlier['product_category'].value_counts()

5076 outlier found

product_category
Mac    5076
Name: count, dtype: int64

In [44]:
Q1 = df ['discount_pct'] .quantile (0.25)
Q3 = df ['discount_pct'] .quantile (0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR 
upper = Q3 +1.5 * IQR
outlier =  df [( df['discount_pct'] < lower) | (df['discount_pct']> upper)]
print ( f"{len(outlier)} outlier found")
outlier['product_category'].value_counts()

0 outlier found

Series([], Name: count, dtype: int64)

In [46]:
mean = df['current_price_inr'].mean()
std = df['current_price_inr'].std()
df['z_score'] = (df['current_price_inr'] -mean) / std 
outlier_z = df [df['z_score'].abs()>3]
outlier_z

Empty DataFrame
Columns: [date, platform, product_category, model_name, condition, launch_price_usd, launch_price_inr, current_price_usd, current_price_inr, discount_pct, sale_event, stock_status, rating, reviews_count, z_score]
Index: []

In [48]:
df['z_score'].describe()

count    8.000000e+04
mean    -2.273737e-17
std      1.000000e+00
min     -1.451103e+00
25%     -7.301210e-01
50%     -1.618942e-01
75%      4.862768e-01
max      2.860072e+00
Name: z_score, dtype: float64

In [54]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [62]:
df['date'] = pd.to_datetime(df['date'],format='%d-%m-%Y')

In [70]:
df[ df ['date'] > '2020-02-23']

,date,platform,product_category,model_name,condition,launch_price_usd,launch_price_inr,current_price_usd,current_price_inr,discount_pct.1,sale_event,stock_status,rating,reviews_count,z_score
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6,New,429,42042,435.81,43322.41,-0.016,NaN,In Stock,4.7,40,-0.693870
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6,New,429,42042,436.49,42320.43,-0.017,NaN,Out of Stock,4.6,84,-0.716078
2,2020-09-23,Amazon,Watch,Apple Watch Series 6,New,429,42042,422.73,40879.36,0.015,NaN,In Stock,4.4,110,-0.748018
3,2020-09-23,Amazon,Watch,Apple Watch Series 6,New,429,42042,425.00,42008.70,0.009,NaN,In Stock,4.8,111,-0.722987
4,2020-09-24,Amazon,Watch,Apple Watch Series 6,New,429,42042,436.22,41984.28,-0.017,NaN,In Stock,4.7,35,-0.723528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-0.015,NaN,In Stock,4.7,1346,0.183218
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,0.019,NaN,In Stock,4.7,802,0.144755
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Referbished,849,83202,657.30,56336.73,0.226,NaN,In Stock,4.2,1020,-0.405418
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Referbished,849,83202,709.49,61361.07,0.164,NaN,In Stock,3.9,710,-0.294058
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,0.017,NaN,Low Stock,4.8,1022,0.186333

In [74]:
df['date'] = df['date'].fillna('No Record')

In [76]:
df['sale_event']=df['sale_event'].fillna('Regular Sale')

In [31]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [32]:
df.columns

Index(['date', 'platform', 'product_category', 'model_name', 'condition',
       'launch_price_usd', 'launch_price_inr', 'current_price_usd',
       'current_price_inr', 'discount_pct.1', 'sale_event', 'stock_status',
       'rating', 'reviews_count'],
      dtype='str')

In [47]:
df=df.rename(columns={'discount_pct.1': 'discount_pct'})

In [50]:
print(df[['launch_price_usd','current_price_usd','discount_pct','rating','reviews_count']].describe())

       launch_price_usd  current_price_usd  discount_pct        rating  \
count      80000.000000       80000.000000  80000.000000  80000.000000
mean         963.959125         782.769855      0.214188      4.450099
std          470.086413         461.673970      0.166973      0.269782
min          329.000000         109.930000     -0.020000      3.800000
25%          599.000000         432.930000      0.067000      4.300000
50%          799.000000         699.740000      0.213000      4.400000
75%         1199.000000         989.112500      0.368000      4.700000
max         1999.000000        2038.970000      0.731000      4.900000

       reviews_count
count   80000.000000
mean     2405.995925
std      1973.630852
min        10.000000
25%       896.000000
50%      1893.500000
75%      3383.000000
max     11526.000000

In [51]:
for col in ['platform','product_category','condition','sale_event','stock_status']:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- platform ---
platform
Flipkart    40043
Amazon      39957
Name: count, dtype: int64

--- product_category ---
product_category
iPhone    28589
Mac       18020
Watch     17865
iPad      15526
Name: count, dtype: int64

--- condition ---
condition
New            59985
Referbished    20015
Name: count, dtype: int64

--- sale_event ---
sale_event
Black Friday             2497
Big Billion Days         1579
Great Indian Festival    1504
Prime Day                1069
Name: count, dtype: int64

--- stock_status ---
stock_status
In Stock        55034
Out of Stock    13475
Low Stock       11491
Name: count, dtype: int64

In [52]:
print("\nSkew of current_price_usd:", df['current_price_usd'].skew())
print("Skew of discount_pct:", df['discount_pct'].skew())

Skew of current_price_usd: 1.1095879589275384
Skew of discount_pct: 0.2452313746186416

In [69]:
df.groupby('platform')['discount_pct'].mean()

platform
Amazon      0.215154
Flipkart    0.213225
Name: discount_pct, dtype: float64

In [56]:
df.groupby('platform')['discount_pct'].agg(['mean', 'median', 'std', 'count'])

              mean  median       std  count
platform
Amazon    0.215154   0.215  0.166882  39957
Flipkart  0.213225   0.212  0.167061  40043

In [68]:
df.groupby('product_category')['current_price_usd'].mean()

product_category
Mac       1382.489812
Watch      398.638561
iPad       573.083382
iPhone     758.674718
Name: current_price_usd, dtype: float64

In [67]:
df.groupby('sale_event')['discount_pct'].mean()

sale_event
Big Billion Days         0.370237
Black Friday             0.314622
Great Indian Festival    0.334461
Prime Day                0.344357
Name: discount_pct, dtype: float64

In [66]:
df.groupby('platform')['rating'].mean()

platform
Amazon      4.450802
Flipkart    4.449397
Name: rating, dtype: float64

In [65]:
pd.crosstab(df['product_category'], df['stock_status'])

stock_status      In Stock  Low Stock  Out of Stock
product_category
Mac                  12673       2474          2873
Watch                12472       2536          2857
iPad                  9957       2494          3075
iPhone               19932       3987          4670

In [70]:
# correlation matrix
print(df[['launch_price_usd','current_price_usd','discount_pct','rating','reviews_count']].corr())

                   launch_price_usd  current_price_usd  discount_pct  \
launch_price_usd           1.000000           0.947179     -0.322066
current_price_usd          0.947179           1.000000     -0.574824
discount_pct              -0.322066          -0.574824      1.000000
rating                    -0.001760           0.110571     -0.310257
reviews_count             -0.096096          -0.265293      0.615356

                     rating  reviews_count
launch_price_usd  -0.001760      -0.096096
current_price_usd  0.110571      -0.265293
discount_pct      -0.310257       0.615356
rating             1.000000       0.003413
reviews_count      0.003413       1.000000

In [71]:
df.to_csv('apple_pricing_cleaned.csv', index=False)